env:
  browser: true
  es6: true
  jest: true

parser: babel-eslint
extends:
  - airbnb-base
  - 'plugin:lodash-fp/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-console: 0
  accessor-pairs: 0
  brace-style: [2, '1tbs']
  comma-dangle: [2, 'always-multiline']
  consistent-return: 0
  dot-location: [2, 'property']
  dot-notation: 2
  eol-last: 2
  eqeqeq: [2, 'allow-null']
  indent: 0
  jsx-quotes: [2, 'prefer-double']
  keyword-spacing: [2, {after: true, before: true}]
  no-bitwise: 0
  no-multi-spaces: 2
  no-inner-declarations: [2, 'functions']
  no-shadow: 2
  no-restricted-syntax: [2, 'WithStatement']
  no-unused-vars: [2, {args: 'none'}]
  no-unused-expressions: 2
  no-useless-concat: 0
  no-use-before-define: [2, {functions: false, variables: false}]
  space-before-blocks: 2
  quotes: [2, 'single', {avoidEscape: true, allowTemplateLiterals: true }]
  valid-typeof: [2, {requireStringLiterals: true}]
  space-before-function-paren: 0
  strict: 2
  no-var: 2
  guard-for-in: 0
  no-param-reassign: [2, { "props": false }]

plugins:
  # https://github.com/babel/eslint-plugin-babel
  - babel
  - jest
  - no-for-of-loops
